# Generated by Django 5.0.2 on 2024-02-15 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='전화번호')),
                ('certification_number', models.CharField(max_length=10, verbose_name='인증번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'db_table': 'sms_certification',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('alpha_code', models.CharField(max_length=10, unique=True, verbose_name='알파벳 코드')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=50, null=True, verbose_name='회원명')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='전화번호')),
                ('gender', models.CharField(default='M', max_length=10, verbose_name='성별')),
                ('birth', models.DateField(null=True, verbose_name='생년월일')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='도시')),
                ('zipcode', models.CharField(max_length=10, null=True, verbose_name='우편번호')),
                ('oauth_type', models.CharField(default=None, max_length=20, verbose_name='oauth type')),
                ('withdrawal_at', models.DateTimeField(null=True, verbose_name='탈퇴일')),
                ('email_verified', models.BooleanField(default=False, verbose_name='이메일 인증여부')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='사용자 포인트')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system_manage.state')),
            ],
            options={
                'db_table': 'auth_profile',
            },
        ),
    ]
